name: Lint
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest
            - uses: actions/cache@v4
              with:
                  path: |
                      node_modules
                      .next/cache
                  key: ${{ runner.os }}-modules-${{ hashFiles('bun.lockb') }}
            - run: bun install
            - run: bunx commitlint --from HEAD~1 --to HEAD --verbose
            - run: bun run format
            - run: bun run typecheck
            - run: bun run lint
